SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(GCC_BIN_DIR /opt/cross-pi-gcc/bin)

SET(CMAKE_C_COMPILER   ${GCC_BIN_DIR}/arm-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER ${GCC_BIN_DIR}/arm-linux-gnueabihf-g++)
SET(CMAKE_ASM_COMPILER ${GCC_BIN_DIR}/arm-linux-gnueabihf-gcc)

SET(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:/opt/cross-pi-libs/lib/pkgconfig")
SET(BOOST_INCLUDEDIR "/opt/cross-pi-libs/include")
SET(CMAKE_LIBRARY_ARCHITECTURE arm-linux-gnueablihf)
SET(CMAKE_FIND_ROOT_PATH /opt/cross-pi-libs)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
