#SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

SET(GCC_BIN_DIR /opt/gcc-10.2.0/bin)

SET(CMAKE_C_COMPILER   ${GCC_BIN_DIR}/gcc-10.2)
SET(CMAKE_CXX_COMPILER ${GCC_BIN_DIR}/g++-10.2)
SET(CMAKE_ASM_COMPILER ${GCC_BIN_DIR}/gcc-10.2)

SET(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:/opt/host-tools/lib/pkgconfig")
SET(BOOST_INCLUDEDIR "/opt/host-tools/include")
SET(CMAKE_LIBRARY_ARCHITECTURE x86_64)
SET(CMAKE_FIND_ROOT_PATH /opt/host-tools)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
#SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
#SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
